[versions]
agp = "9.4.1"
kotlin = "2.4.21"
ksp = "2.3.12"
hilt = "2.60.1"
compose = "2026.09.00"
firebase = "35.0.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version = "4.5.0" }
crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.8" }
